[package]
name = "theorylang"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = "0.12.0"
clap = { version = "4.5.53", features = ["derive"] }
lexgen = "0.16.0"
lexgen_util = "0.16.0"
rustyline = "17.0.2"

[profile.release]
# lto = true
# debug = true
